### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by eheydrick** [sensu-plugins/sensu-plugins-lvm#4]
We should release a new version to address #3. It should be a major version since moving from `di-ruby-lvm` to `chef-ruby-lvm` will prompt for input if you don't uninstall `di-ruby-lvm` first. Looks like the release pipeline was never fully setup and @insom has been handling releases.

**Comment by insom** [comment]
Thanks for this! I've pushed a new release of the gem.

I would like to set up the release pipeline, I just don't know how. Is that something I can do and are there docs or examples I should look at?
