### ISSUE TITLE
LVM data and metadata empty values on RHEL 7.3

### ISSUE THREAD

**Issue by aivaraslaimikis** [sensu-plugins/sensu-plugins-lvm#5]
Hi,

 I noticed that LVM think pool metadata and data monitoring stopped to work. It looks like in volume no longer have data_percent and metadata_percent variables.
 I was able to recreate issue and it looks like upgrade from RHEL 7.2 to RHEL 7.3 break monitoring, more specific upgrade of:

lvm2-2.02.130-5.el7_2.6.x86_64 -> lvm2-2.02.166-1.el7_3.2.x86_64
lvm2-libs-2.02.130-5.el7_2.6.x86_64 -> lvm2-libs-2.02.166-1.el7_3.2.x86_64

 Maybe someone found same issue too with newer lvm2 packages and found workaround?
 Thanks for any info.

Aivaras

**Comment by aivaraslaimikis** [comment]
Found issue https://github.com/chef/chef-ruby-lvm-attrib/pull/3

**Comment by majormoses** [comment]
@aivaraslaimikis thanks for the report, I reviewed your change over there and it looks good to me. Would you be willing to put together a similar PR over here?

**Comment by aivaraslaimikis** [comment]
@majormoses PR merged. What do you mean by similar PR over here? Is there is other attributes generate script?

**Comment by majormoses** [comment]
no I am saying putting some additional guards in this check to ensure that it does not break when this data is present (I assume that until we bump deps on it someone is broken) in this plugin. I guess it has been released now (was not at the time I reponded) so we might just want to bump deps on it and call it good.

**Comment by aivaraslaimikis** [comment]
Maybe first dependency lock would help?
https://github.com/aivaraslaimikis/sensu-plugins-lvm/commit/9e66bc21214b18aad543e0619981881b2b30c203

**Comment by majormoses** [comment]
yup, that should work except that the changelog entry needs to be under `## [Unreleased]` we don't modify previous releases and make new releases. After that a PR for that would be accepted.

**Comment by aivaraslaimikis** [comment]
I changed chef-ruby-lvm dependency version, because 0.2.2 release not supported new chef-ruby-lvm-attrib versions.

**Comment by majormoses** [comment]
closed per #6
